language: node_js
node_js:
  - "stable"
  - "6"
  - "7"
  - "8"
  - "9"
  - "11"
script: npm run-script pretest && npm run-script coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
